fix: fixing header with a11y and mobile
CityOfPhiladelphia/phila-ui pull request #46
Opened 2019-12-06 17:44 UTC by alejandroxlopez

Adding some a11y code, and basic mobile support (temporary)

2019-12-06 18:19 UTC, ibdf commented on src/components/AppHeader/AppHeader.vue
> +      font-family: 'Montserrat', 'Tahoma', sans-serif;
use bulma variables instead of hard coding it

2019-12-06 18:22 UTC, ibdf commented on src/components/AppHeader/AppHeader.vue
> +      font-weight: 400;
use bulma variables instead of hard coding it

2019-12-06 18:27 UTC, ibdf commented on src/components/AppHeader/AppHeader.vue
> +        <!-- Menu Desktop -->
Need to remove old comments

2019-12-06 18:35 UTC, ibdf requested changes
1. Remove mobile menu from within header
2. make mobile menu it's own components
3. add an extra  named slot mobile-menu to AppHeader

2020-01-06 16:22 UTC, karissademi approved these changes
We discussed this in our biweeky meeting. 👍

2020-01-06 17:01 UTC, ibdf approved these changes

2020-01-06 17:02 UTC, merged